=== Mochatr/technologie_xml/releve.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="releve">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dateReleve" type="xs:date"/>
                <xs:element name="solde" type="xs:decimal"/>
                <xs:element name="operations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="operation" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="type" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="CREDIT"/>
                                                <xs:enumeration value="DEBIT"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="date" type="xs:date" use="required"/>
                                    <xs:attribute name="montant" type="xs:decimal" use="required"/>
                                    <xs:attribute name="description" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="dateDebut" type="xs:date" use="required"/>
                        <xs:attribute name="dateFin" type="xs:date" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="RIB" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Mochatr/technologie_xml/releve_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<releve xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="releve.xsd"
        RIB="011112222333344445555666">
    <dateReleve>2021-11-10</dateReleve>
    <solde>14500</solde>
    <operations dateDebut="2021-01-01" dateFin="2021-01-30">
        <operation type="CREDIT" date="2021-01-01" montant="9000" description="Vers Espèce"></operation>
        <operation type="DEBIT" date="2021-01-11" montant="3400" description="Chèque Guichet"></operation>
        <operation type="DEBIT" date="2021-01-15" montant="120" description="Prélèvement Assurance"></operation>
        <operation type="CREDIT" date="2021-01-25" montant="70000" description="Virement .."></operation>
    </operations>
</releve>
